[package]
name = "haste-config"
version = "0.1.1"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
haste-fhir-model = { path = "../fhir-model" }
haste-fhir-operation-error = { path = "../fhir-operation-error", features = [
    "derive",
] }
tracing = "0.1.41"
