[package]
name = "oxidized-config"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
oxidized-fhir-model = { path = "../fhir-model" }
oxidized-fhir-operation-error = { path = "../fhir-operation-error", features = [
    "derive",
] }
