[package]
name = "haste-health"
version = "0.1.0"
edition = "2024"
description = "Haste Health binary."
publish = false
license = "GPL-3.0"

# [profile.release]
# strip = true    # Automatically strip symbols from the binary.
# opt-level = "z" # Optimize for size in release builds.

[workspace]
resolver = "3"
members = [
    "crates/access-control",
    "crates/artifacts",
    "crates/codegen",
    "crates/config",
    "crates/fhir-client",
    "crates/fhir-generated-ops",
    "crates/fhir-model",
    "crates/fhir-operation-error",
    "crates/fhir-operation-error-derive",
    "crates/fhir-ops",
    "crates/fhir-ops-derive",
    "crates/fhir-search",
    "crates/fhir-serialization-json",
    "crates/fhir-serialization-json-derive",
    "crates/fhir-terminology",
    "crates/fhirpath",
    "crates/hl7v2",
    "crates/indexing-worker",
    "crates/jwt",
    "crates/macro-loads",
    "crates/reflect",
    "crates/reflect-derive",
    "crates/repository",
    "crates/server",
]

[workspace.package]
version = "0.1.1"
authors = ["Haste Health"]
license = "BSD-3-Clause"
homepage = "https://haste.health"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
dialoguer = "0.12.0"
jsonwebtoken = { version = "10.2.0", features = ["rust_crypto"] }
haste-codegen = { path = "./crates/codegen" }
haste-config = { path = "./crates/config" }
haste-fhir-client = { path = "./crates/fhir-client", features = ["http"] }
haste-fhir-model = { path = "./crates/fhir-model" }
haste-fhir-operation-error = { path = "./crates/fhir-operation-error" }
haste-fhir-search = { path = "./crates/fhir-search" }
haste-fhir-serialization-json = { path = "./crates/fhir-serialization-json" }
haste-fhirpath = { path = "./crates/fhirpath" }
haste-indexing-worker = { path = "./crates/indexing-worker" }
haste-jwt = { path = "./crates/jwt" }
haste-repository = { path = "./crates/repository" }
haste-server = { path = "./crates/server" }
quote = "1.0.40"
reqwest = { version = "0.12" }
serde = "1.0.228"
serde_json = "1.0"
thiserror = "2.0.12"
tokio = { version = "1", features = ["full"] }
toml = "0.9.8"
json-patch = "4.1.0"
