[package]
name = "haste-macro-loads"
version = { workspace = true }
edition = { workspace = true }
description = "Macro loads for Haste Health."
license = { workspace = true }
homepage = { workspace = true }

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
syn = "2.0.106"
walkdir = "2.5.0"
