[package]
name = "haste-macro-loads"
version = "0.1.1"
edition = "2024"
description = "Macro loads for Haste Health."
license = "GPL-3.0"
homepage = "https://haste.health"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
syn = "2.0.106"
walkdir = "2.5.0"
