[package]
name = "haste-repository"
version = { workspace = true }
edition = { workspace = true }
description = "Repository/storage for Haste Health resources."
license = { workspace = true }
homepage = { workspace = true }

[dependencies]
moka = { version = "0.12.11", features = ["future"] }
nanoid = "0.4.0"
haste-fhir-client = { path = "../fhir-client" }
haste-fhir-model = { path = "../fhir-model", features = ["sqlx"] }
haste-fhir-operation-error = { path = "../fhir-operation-error", features = [
    "derive",
] }
haste-jwt = { path = "../jwt", features = ["sqlx"] }
haste-reflect = { path = "../reflect", features = ["derive"] }
regex = "1.12.2"
serde = "1.0.219"
serde_json = "1.0.142"
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "tls-native-tls",
    "postgres",
    "time",
] }
sqlx-postgres = "0.8.6"
tokio = { version = "1.47.1", features = ["sync"] }
tracing = "0.1.41"
