[package]
name = "oxidized-jwt"
version = "0.1.0"
edition = "2024"

[features]
sqlx = ["dep:sqlx"]

[dependencies]
serde = "1.0.228"
oxidized-fhir-model = { path = "../fhir-model" }
oxidized-fhir-operation-error = { path = "../fhir-operation-error" }
sqlx = { version = "0.8", optional = true }
