[package]
name = "haste-jwt"
version = "0.1.1"
edition = "2024"
description = "JWT utilities and claims for Haste Health."
license = "GPL-3.0"
homepage = "https://haste.health"

[features]
sqlx = ["dep:sqlx"]
reflect = ["dep:haste-reflect"]

[dependencies]
haste-fhir-model = { path = "../fhir-model" }
haste-fhir-operation-error = { path = "../fhir-operation-error" }
haste-reflect = { path = "../reflect", optional = true }
serde = "1.0.228"
sqlx = { version = "0.8", optional = true }
