[package]
name = "oxidized-fhir-operation-error-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
oxidized-fhir-model = { path = "../fhir-model" }
quote = "1.0.40"
syn = "2.0.104"
proc-macro2 = "1.0.95"
