[package]
name = "oxidized-server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
axum = { version = "0.8.4", features = ["macros"] }
axum-extra = { version = "0.10.1", features = ["typed-routing"] }
base64 = "0.22.1"
chrono = "0.4.41"
clap = { version = "4.5.45", features = ["derive"] }
dotenvy = "0.15.7"
json-patch = "4.0.0"
jsonwebtoken = "9.3.1"
maud = { version = "0.27.0", features = ["axum"] }
mime_guess = "2.0.5"
oxidized-access-control = { path = "../access-control" }
oxidized-artifacts = { path = "../artifacts" }
oxidized-config = { path = "../config" }
oxidized-fhir-client = { path = "../fhir-client", features = ["http", "axum"] }
oxidized-fhir-generated-ops = { path = "../fhir-generated-ops" }
oxidized-fhir-model = { path = "../fhir-model", features = ["sqlx"] }
oxidized-fhir-operation-error = { path = "../fhir-operation-error", features = [
    "derive",
    "axum",
] }
oxidized-fhir-ops = { path = "../fhir-ops" }
oxidized-fhir-search = { path = "../fhir-search" }
oxidized-fhir-serialization-json = { path = "../fhir-serialization-json" }
oxidized-fhir-terminology = { path = "../fhir-terminology" }
oxidized-fhirpath = { path = "../fhirpath" }
oxidized-jwt = { path = "../jwt" }
oxidized-reflect = { path = "../reflect", features = ["derive"] }
oxidized-repository = { path = "../repository" }
petgraph = "0.8.3"
rand = "0.8"
regex = "1.11.1"
reqwest = { version = "0.12" }
rsa = "0.9.8"
rust-embed = { version = "8.9.0", features = ["axum-ex"] }
sendgrid = "0.24.1"
serde = "1.0.219"
serde_html_form = "0.2.8"
serde_json = "1.0.140"
sha1 = "0.10.6"
sha2 = "0.10.9"
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "tls-native-tls",
    "postgres",
    "time",
] }
sqlx-postgres = "0.8.6"
thiserror = "2.0.12"
tokio = { version = "1", features = ["full"] }
tower = "0.5.2"
tower-http = { version = "0.6.6", features = [
    "fs",
    "cors",
    "normalize-path",
    "compression-gzip",
] }
tower-sessions = "0.14.0"
tower-sessions-sqlx-store = { version = "0.15.0", features = ["postgres"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
typify = "0.4.2"
url = "2.5.4"
zxcvbn = "3.1.0"
