[package]
name = "haste-fhir-generated-ops"
version = "0.1.0"
edition = "2024"

[dependencies]
haste-fhir-model = { path = "../fhir-model" }
haste-fhir-operation-error = { path = "../fhir-operation-error" }
haste-fhir-ops = { path = "../fhir-ops", features = ["derive"] }
