[package]
name = "haste-reflect"
version = { workspace = true }
edition = { workspace = true }
description = "Reflection utilities for Haste Health."
license = { workspace = true }
homepage = { workspace = true }

[features]
derive = ["dep:haste-reflect-derive"]

[dependencies]
haste-reflect-derive = { path = "../reflect-derive", version = "0.*", optional = true }
