[package]
name = "oxidized-reflect"
version = "0.1.0"
edition = "2024"

[features]
derive = ["dep:oxidized-reflect-derive"]

[dependencies]
oxidized-reflect-derive = { path = "../reflect-derive", optional = true }
