[package]
name = "haste-reflect"
version = "0.1.0"
edition = "2024"

[features]
derive = ["dep:haste-reflect-derive"]

[dependencies]
haste-reflect-derive = { path = "../reflect-derive", optional = true }
