[package]
name = "fhir-operation-error"
version = "0.1.0"
edition = "2024"

[features]
derive = []

[dependencies]
anyhow = "1.0.98"
fhir-operation-error-derive = { path = "../fhir-operation-error-derive" }
fhir-model = { path = "../fhir-model" }
