[package]
name = "oxidized-fhir-ops"
version = "0.1.0"
edition = "2024"

[features]
derive = ["dep:oxidized-fhir-ops-derive"]

[dependencies]
oxidized-fhir-ops-derive = { path = "../fhir-ops-derive", optional = true }
oxidized-fhir-model = { path = "../fhir-model" }
oxidized-fhir-operation-error = { path = "../fhir-operation-error" }
oxidized-repository = { path = "../repository" }
