[package]
name = "fhir-client"
version = "0.1.0"
edition = "2024"

[features]
axum = ["dep:axum"]

[dependencies]
fhir-model = { path = "../fhir-model" }
axum = { version = "0.8.4", optional = true }
http = "1.3.1"
json-patch = "4.0.0"
thiserror = "2.0.12"
