name: Release
on:
  release:
    types: [published]

jobs:
  linux:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build
        run: cd backend && cargo build --release
      - name: Test
        run: mv backend/target/release/oxidized-health ./oxidized-health_linux
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            oxidized-health_linux
  #   windows:
  #     runs-on: windows-latest
  #     permissions:
  #       packages: write
  #       contents: write
  #     steps:
  #       - name: Checkout
  #         uses: actions/checkout@v5
  #       - name: Build
  #         run: cd backend && cargo build --release
  #       - name: Test
  #         run: mv backend/target/release/oxidized-health ./oxidized-health_windows
  #       - name: Release
  #         uses: softprops/action-gh-release@v2
  #         with:
  #           files: |
  #             oxidized-health_windows
  mac:
    runs-on: macos-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build
        run: cd backend && cargo build --release
      - name: Test
        run: mv backend/target/release/oxidized-health ./oxidized-health_macos
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            oxidized-health_macos
